# Dont do like this

In [8]:
import numpy as np


In [9]:
A = np.random.randn(5)
print(A)

[ 0.64541369  0.30937012 -1.42612925  0.72631455  1.8243082 ]


In [10]:
A.shape

(5,)

In [11]:
print(A.T)

[ 0.64541369  0.30937012 -1.42612925  0.72631455  1.8243082 ]


In [12]:
np.dot(A , A.T)

6.401746548943784

# Correct Way - Always make a row or bector column

In [13]:
a = np.random.randn(5 , 1)
print(a)

[[ 0.07511512]
 [-0.65504134]
 [-0.18147967]
 [-0.56337817]
 [-0.25915482]]


In [15]:
print(a.shape)

(5, 1)


In [16]:
a.T

array([[ 0.07511512, -0.65504134, -0.18147967, -0.56337817, -0.25915482]])

In [17]:
print(np.dot(a , a.T))

[[ 0.00564228 -0.04920351 -0.01363187 -0.04231822 -0.01946645]
 [-0.04920351  0.42907916  0.11887669  0.36903599  0.16975712]
 [-0.01363187  0.11887669  0.03293487  0.10224169  0.04703133]
 [-0.04231822  0.36903599  0.10224169  0.31739496  0.14600217]
 [-0.01946645  0.16975712  0.04703133  0.14600217  0.06716122]]
