In [16]:
import numpy as np
np.random.seed(0)

In [17]:
#computing manually reciprocal
def compute_reciprocal(value):
    output = np.empty(len(value))
    for i , val in enumerate(value):
        output[i] = 1.0/val
     
    return output

value = np.random.randint(1 , 10 , size=5)
compute_reciprocal(value)
        

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [20]:
bing_arr = np.random.randint(1,100 , size=1000000)
%timeit compute_reciprocal(bing_arr)

1.77 s ± 16.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Functions

In [21]:
print(compute_reciprocal(value))
print(1.0/value)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [25]:
%timeit 1.0/bing_arr

1.55 ms ± 18.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)




Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated operations on values in NumPy arrays. Ufuncs are extremely flexible – before we saw an operation between a scalar and an array, but we can also operate between two arrays:


In [26]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [28]:
x = np.arange(9).reshape(3 , 3)
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [30]:
y = np.arange(4)
print(y)
print(y+1)
print(y-1)
print(y/2)

print(y//2)
print(y*2)

[0 1 2 3]
[1 2 3 4]
[-1  0  1  2]
[0.  0.5 1.  1.5]
[0 0 1 1]
[0 2 4 6]


In [32]:
print(-y)
print(y**3)
print(y %2)

[ 0 -1 -2 -3]
[ 0  1  8 27]
[0 1 0 1]


In [33]:
-(0.5*y +1) **2

array([-1.  , -2.25, -4.  , -6.25])

# numpy function

Operator 	Equivalent ufunc 	Description
+ (+) np.add 	Addition (e.g., 1 + 1 = 2)
- (-) np.subtract 	Subtraction (e.g., 3 - 2 = 1)
- (-) np.negative 	Unary negation (e.g., -2)
* (*) np.multiply 	Multiplication (e.g., 2 * 3 = 6)
* / 	np.divide 	Division (e.g., 3 / 2 = 1.5)
* // 	np.floor_divide 	Floor division (e.g., 3 // 2 = 1)
* ** 	np.power 	Exponentiation (e.g., 2 ** 3 = 8)
* % 	np.mod 	Modulus/remainder (e.g., 9 % 4 = 1)

In [34]:
type(y)

numpy.ndarray

In [38]:
x = np.array([-2, 4 , -6 , -8])
type(x)
abs(x)

array([2, 4, 6, 8])

In [39]:
np.absolute(x)

array([2, 4, 6, 8])

In [40]:
np.abs(x)

array([2, 4, 6, 8])

This ufunc can also handle complex data, in which the absolute value returns the magnitude:

In [43]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

# Trigonometric function

In [48]:
theta = np.linspace(0 , np.pi , 5)

In [49]:
theta

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [55]:
print(np.sin(theta) , np.cos(theta) , np.tan(theta) , )

[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16] [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00] [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]


In [56]:
x = [-1 , 0 , 1]

In [59]:
#inverse Trigonometric function
print(np.arccos(x) , np.arcsin(x) , np.arctan(x))

[3.14159265 1.57079633 0.        ] [-1.57079633  0.          1.57079633] [-0.78539816  0.          0.78539816]


# Exponent and logarithmics

In [60]:
x = [2 , 3 , 4]

print("x = " , x)
print("e^x = " , np.exp(x))
print("2^x = " , np.exp2(x))
print("3^x= " , np.power(3 , x))

x =  [2, 3, 4]
e^x =  [ 7.3890561  20.08553692 54.59815003]
2^x =  [ 4.  8. 16.]
3^x=  [ 9 27 81]


In [63]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))


x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


There are also some specialized versions that are useful for maintaining precision with very small input:

In [66]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))



exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [67]:
from scipy import special

In [69]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [70]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [73]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x , 10 , out=y)

array([ 0., 10., 20., 30., 40.])

In [75]:
y = np.zeros(10)
np.power( 2 , x , out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


# Aggregates

In [76]:
x = np.arange(1, 5)

A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, calling reduce on the add ufunc returns the sum of all elements in the array:

In [79]:
np.add.reduce(x)

10

In [80]:
np.multiply.reduce(x)

24

In [81]:
np.add.accumulate(x)

array([ 1,  3,  6, 10])

In [82]:
np.multiply.accumulate(x)

array([ 1,  2,  6, 24])


Outer products

Finally, any ufunc can compute the output of all pairs of two different inputs using the outer method. This allows you, in one line, to do things like create a multiplication table:


In [85]:
np.multiply.outer(x , x)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])