In [2]:
import numpy as np

In [2]:
rand = np.random.RandomState(42)
x = rand.randint(100 , size = 10)

In [3]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [6]:
ind = [3 , 4, 5]
x[ind]

array([71, 60, 20])

In [7]:
[x[3] , x[4] , x[5]]

[71, 60, 20]

In [8]:
ind = np.array([[3 , 7] , [4   ,5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [11]:
X = np.arange(12).reshape((3 , 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [14]:
np.random.seed(42)
x = np.random.randn(100)

# compute a histogram by hand
bins = np.linspace(-5, 5, 20)
counts = np.zeros_like(bins)

# find the appropriate bin for each x
i = np.searchsorted(bins, x)

# add 1 to each of these bins
np.add.at(counts, i, 1)

In [15]:
i

array([11, 10, 11, 13, 10, 10, 13, 11,  9, 11,  9,  9, 10,  6,  7,  9,  8,
       11,  8,  7, 13, 10, 10,  7,  9, 10,  8, 11,  9,  9,  9, 14, 10,  8,
       12,  8, 10,  6,  7, 10, 11, 10, 10,  9,  7,  9,  9, 12, 11,  7, 11,
        9,  9, 11, 12, 12,  8,  9, 11, 12,  9, 10,  8,  8, 12, 13, 10, 12,
       11,  9, 11, 13, 10, 13,  5, 12, 10,  9, 10,  6, 10, 11, 13,  9,  8,
        9, 12, 11,  9, 11, 10, 12,  9,  9,  9,  7, 11, 10, 10, 10])

# Sorting Arrays


In [23]:
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:]) #find minimum element from i to end
        (x[i] , x[swap])=(x[swap] , x[i])
    return x

In [32]:
x = np.random.randint(100 , size = 10000)
%timeit selection_sort(x)  # O( n^2)

69.9 ms ± 292 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Fast Sorting in NumPy: np.sort and np.argsort

In [33]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x) # O(n log(n))

array([1, 2, 3, 4, 5])

In [34]:
x.sort()

In [35]:
#if you want indices
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [36]:
x[i]

array([1, 2, 3, 4, 5])

In [4]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [38]:
#sort along column wise
np.sort(X , axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [39]:
#sort along row wise
np.sort(X , axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])


# Partial Sorts: Partitioning

Sometimes we're not interested in sorting the entire array, but simply want to find the k smallest values in the array. NumPy provides this in the np.partition function. np.partition takes an array and a number K; the result is a new array with the smallest K values to the left of the partition, and the remaining values to the right, in arbitrary order:


In [40]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x , 3)

array([2, 1, 3, 4, 6, 5, 7])

In [41]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

In [42]:
np.argpartition(X , 2 , axis=1) #indices

array([[1, 3, 0, 2, 4, 5],
       [0, 4, 3, 2, 1, 5],
       [4, 1, 3, 2, 0, 5],
       [3, 1, 2, 0, 4, 5]])

In [22]:
differences = X[:, np.newaxis, :] - X[np.newaxis, :, :]
differences.shape

(4, 4, 6)

In [23]:
differences

array([[[ 0,  0,  0,  0,  0,  0],
        [ 4, -3,  0,  0,  3,  2],
        [-1,  1,  2,  0,  5,  2],
        [ 1,  2,  3,  4, -3,  4]],

       [[-4,  3,  0,  0, -3, -2],
        [ 0,  0,  0,  0,  0,  0],
        [-5,  4,  2,  0,  2,  0],
        [-3,  5,  3,  4, -6,  2]],

       [[ 1, -1, -2,  0, -5, -2],
        [ 5, -4, -2,  0, -2,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 2,  1,  1,  4, -8,  2]],

       [[-1, -2, -3, -4,  3, -4],
        [ 3, -5, -3, -4,  6, -2],
        [-2, -1, -1, -4,  8, -2],
        [ 0,  0,  0,  0,  0,  0]]])

In [19]:
X[:, np.newaxis, :].shape

(4, 1, 6)

In [18]:
X[np.newaxis, :, :].shape

(1, 4, 6)

In [24]:
differences ** 2

array([[[ 0,  0,  0,  0,  0,  0],
        [16,  9,  0,  0,  9,  4],
        [ 1,  1,  4,  0, 25,  4],
        [ 1,  4,  9, 16,  9, 16]],

       [[16,  9,  0,  0,  9,  4],
        [ 0,  0,  0,  0,  0,  0],
        [25, 16,  4,  0,  4,  0],
        [ 9, 25,  9, 16, 36,  4]],

       [[ 1,  1,  4,  0, 25,  4],
        [25, 16,  4,  0,  4,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 4,  1,  1, 16, 64,  4]],

       [[ 1,  4,  9, 16,  9, 16],
        [ 9, 25,  9, 16, 36,  4],
        [ 4,  1,  1, 16, 64,  4],
        [ 0,  0,  0,  0,  0,  0]]])