In [1]:
import numpy as np

In [2]:
y = np.array([1 , 2 , 3, 4])
y

array([1, 2, 3, 4])

In [3]:
print(type(y))

<class 'numpy.ndarray'>


In [4]:
y = np.array([3.14 , 5 , 4])
y

array([3.14, 5.  , 4.  ])



Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):


In [7]:
y = np.array([4,5,6,3] , dtype='float')
y


array([4., 5., 6., 3.])

In [8]:
np.array([range(i , i+3) for i in [2 , 4 , 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Basic array Form Np

In [11]:
np.zeros((2,4) , dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((3,5) , 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [62]:
np.random.randn(3,5) #it fills array as per standard normal distribution value

array([[ 1.70082593,  0.52442778,  1.42842073, -1.28667828,  0.81866354],
       [-1.78212049,  0.55290066, -0.10186997, -0.20617178,  1.07295023],
       [-0.73387543,  0.01191689, -1.74949589,  0.9888489 ,  1.81422744]])

In [64]:
np.random.random((2,3)) #random. random() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).

array([[0.31775845, 0.65766874, 0.58413186],
       [0.97092561, 0.20162007, 0.99005532]])

In [66]:

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))



array([[ 0.01143785,  1.06867496,  0.76795428],
       [ 0.56325079,  0.45572532,  0.31761102],
       [ 2.08366466, -0.61555141, -0.24843684]])

In [69]:
np.random.randint(0 , 10 , (3 , 4)) # Create a 3x4 array of random integers in the interval [0, 10)

array([[3, 1, 1, 4],
       [2, 3, 2, 9],
       [1, 1, 3, 1]])

In [70]:
np.eye(3,4) #create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [73]:
np.empty(3)
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location

array([1., 1., 1.])

1. bool_ 	Boolean (True or False) stored as a byte
2. int_ 	Default integer type (same as C long; normally either int64 or int32)
3. intc 	Identical to C int (normally int32 or int64)
4. intp 	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
5. int8 	Byte (-128 to 127)
6. int16 	Integer (-32768 to 32767)
7. int32 	Integer (-2147483648 to 2147483647)
8. int64 	Integer (-9223372036854775808 to 9223372036854775807)
9. uint8 	Unsigned integer (0 to 255)
10. uint16 	Unsigned integer (0 to 65535)
11. uint32 	Unsigned integer (0 to 4294967295)
12. uint64 	Unsigned integer (0 to 18446744073709551615)
13. float_ 	Shorthand for float64.
14. float16 	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
15. float32 	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
16. float64 	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
17. complex_ 	Shorthand for complex128.
18. complex64 	Complex number, represented by two 32-bit floats
19. complex128 	Complex number, represented by two 64-bit floats

# Basic Numpy array

Attribute of the array

In [120]:
np.random.seed(0) #means same random value generated each time whenever this will run

x1 = np.random.randint(10 , size = 6)
x2 = np.random.randint(10 , size = (3,4))
x3 = np.random.randint(10 , size = (3,4,5))

In [80]:
print(x3.ndim , x3.shape , x3.size)

3 (3, 4, 5) 60


In [83]:
print(x3.dtype)

int64


In [86]:
print(str(x3.itemsize) +" bytes " , str(x3.nbytes) + " bytes")

8 bytes  480 bytes


In [87]:
x1

array([5, 0, 3, 3, 7, 9])

In [88]:
x1[-1]

9

In [89]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [90]:
x2[0 ,0]

3

In [91]:
#array slicing x[start:stop:step]

In [99]:
y = np.arange(10 , dtype='int')

In [101]:
y[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [102]:
y[4:]

array([4, 5, 6, 7, 8, 9])

In [103]:
y[4:6]

array([4, 5])

In [107]:
y[::4] #every other element

array([0, 4, 8])

In [109]:
y[2::2]  #every other element starting from index 2

array([2, 4, 6, 8])

In [112]:
y[::-1]  # all elements in reversed order

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [113]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [114]:
x2[:2 , :3] #two rows 3 column

array([[3, 5, 2],
       [7, 6, 8]])

In [115]:
x2[: , :3]

array([[3, 5, 2],
       [7, 6, 8],
       [1, 6, 7]])

In [116]:
x2[::-1 , ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [121]:
x2[:2 , :2]

array([[3, 5],
       [7, 6]])

Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [124]:
x2_sub = x2[:2 , :2]
x2_sub[0 , 0]=4

In [125]:
x2_sub

array([[4, 5],
       [7, 6]])

In [126]:
x2

array([[4, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])



This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.


# Creating copies of the array



If we now modify this subarray, the original array is not touched:


In [127]:
x2_sub_copy = x2[:2 , :3].copy()
x2_sub_copy

array([[4, 5, 2],
       [7, 6, 8]])

In [128]:
x2_sub_copy[0 , 2]=45
x2_sub_copy

array([[ 4,  5, 45],
       [ 7,  6,  8]])

In [129]:
x2

array([[4, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

# Reshaping 

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

In [130]:
grid = np.arange(1,10).reshape(3,3)

In [131]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
y = np.array([1,5,6,87])
print(y.shape)
y.reshape((4 , 1))

(4,)


array([[ 1],
       [ 5],
       [ 6],
       [87]])

In [141]:
y[: , np.newaxis]

array([[ 1],
       [ 5],
       [ 6],
       [87]])

# Array Concatenation and Splitting 

np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument

In [143]:
x = np.array([1 , 3 , 4 ])
y = np.array([3 , 45 , 6 , 6])
np.concatenate([x,y])

array([ 1,  3,  4,  3, 45,  6,  6])

In [144]:
z = np.array([4 ,8,9,3])
np.concatenate([x , y , z])

array([ 1,  3,  4,  3, 45,  6,  6,  4,  8,  9,  3])

In [145]:
grid = np.arange(2 , 8).reshape(2,3)

In [147]:
grid

array([[2, 3, 4],
       [5, 6, 7]])

In [148]:
np.concatenate([grid , grid]) # concatenate along the first axis

array([[2, 3, 4],
       [5, 6, 7],
       [2, 3, 4],
       [5, 6, 7]])

In [149]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid , grid] , axis=1)

array([[2, 3, 4, 2, 3, 4],
       [5, 6, 7, 5, 6, 7]])

In [150]:
np.concatenate([x , grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

In [151]:
np.vstack([x , grid])

array([[1, 3, 4],
       [2, 3, 4],
       [5, 6, 7]])

In [155]:
h= np.array([[1],[2]])
np.hstack([grid ,h])

array([[2, 3, 4, 1],
       [5, 6, 7, 2]])

# Splitting of the arrays

np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:

In [201]:
x = [2 , 3 ,4, 48,5 ,5 ,65 , 4 ]
x1 , x2 , x3 , x4 = np.split(x , [2,1,4])

In [203]:
print(x1 , x2 , x3 , x4)


[2 3] [] [ 3  4 48] [ 5  5 65  4]


In [204]:


grid = np.arange(16).reshape((4, 4))
grid



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [210]:
uppr , lower= np.vsplit(grid , [1])

In [211]:
print(uppr , lower)

[[0 1 2 3]] [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [212]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
