In [1]:
import numpy as np



In [2]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [6]:
x = np.zeros(4 , dtype='int')
x

array([0, 0, 0, 0])

In [10]:
x = np.zeros(4 , dtype={'names':('name' , 'age' , 'weight') , 'formats':('U10' ,'i4' , 'f8')})

In [11]:
x

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [12]:
x['name']=name
x['age']=age
x['weight'] = weight

In [25]:
x

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [14]:
x['name'][0]

'Alice'

In [15]:
x['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [16]:
x[x['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [17]:
np.dtype({'names':('name' , 'age' , 'weight') , 'formats':(np.str , int , np.float)})

dtype([('name', '<U'), ('age', '<i8'), ('weight', '<f8')])

In [18]:
np.dtype({'names':('name' , 'age' , 'weight') , 'formats':((np.str_,10) , int , np.float)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f8')])

In [20]:
np.dtype('S10 , i4 , f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [22]:
np.dtype('b , i4 , f8') #b for byte

dtype([('f0', 'i1'), ('f1', '<i4'), ('f2', '<f8')])

It is possible to define even more advanced compound types. For example, you can create a type where each element contains an array or matrix of values. Here, we'll create a data type with a mat component consisting of a 3×3 floating-point matrix:

In [23]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])



(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
data_rec = x.view(np.recarray)
data_rec

rec.array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
           ('Doug', 19, 61.5)],
          dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [27]:
data_rec.age

array([25, 45, 37, 19], dtype=int32)

In [29]:
%timeit x['age']
%timeit data_rec['age']
%timeit data_rec.age

156 ns ± 6.51 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
2.89 µs ± 72.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.56 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
